# SITE CONFIGURATION
title: labexam # your site title
author: Mah # You :P
description: > # Meta description of Homepage
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/labexam" # the subpath of your site, e.g. /blog
url: "http://mahch40.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Mah Cheraghi
  links:
    - https://twitter.com/ali
    - https://www.facebook.com/ali
    - https://www.linkedin.com/in/ali
    - https://plus.google.com/ali
    - https://github.com/ali
    - https://keybase.io/ali

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/Home'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
 Welcome
hero_img: posts/labexam_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/labexam_lg.jpg

email: ali@gmail.com # email for form submission

twitter_username: ali # replace with your_twitter_username or comment to remove link from footer
github_username:  ali # replace with your_github_username or comment to remove link from footer
instagram_username: ali # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: ali # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-labexam # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - labexam.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
